version: "2"

services:
  ss-server:
    build:
      context: ./ss-server
    ports:
      - "${SSM_PORT}:6001"
      - "65000-65200:65000-65200"
    restart: always
  ss-mgr:
    build:
      context: ./ss-mgr
    ports:
      - "${SSMGR_PORT}:6002"
    depends_on:
      - ss-server
  ss-gui:
    build:
      context: ./ss-gui
    ports:
      - "${SSGUI_PORT}:80"
    depends_on:
      - ss-mgr      